#!/bin/bash

function findgit() {
  local directory=$1
  if [ -d "$directory"  ] && [ "$directory" != "/" ]; then
    if [ -d "$directory/.git" ] ; then
      cd "$directory"
      echo "$PWD"
      exit
    else
      findgit "$directory/.."
    fi
  else
    echo "no parent git found"
  fi
}

findgit $PWD
