#!/bin/bash

pre_install() {
  if [ $SPIN ] ; then
    sudo apt install -y silversearcher-ag
    rm ~/.gitconfig ~/.zshrc
  fi
}

install() {
  ./create-symlinks
}

post_install() {
  if [ $SPIN ] ; then
    for repo in $(find $HOME/src/github.com/Shopify -maxdepth 1 -mindepth 1); do
      cd $repo
      if [[ $(find . -name "*.rb" | wc -l) -gt 0 ]] ; then
        export GEM_HOME="$HOME/.gem"
        gem install ripper-tags
        export PATH=$PATH:$HOME/.gem/bin
        $HOME/bin/git-ctags
      fi
    done
  fi
}

main() {
  pre_install
  install
  post_install
}

main
