#!/bin/bash

pre_install() {
  if [ $SPIN ] ; then
    sudo apt install -y silversearcher-ag fd-find
    rm ~/.gitconfig ~/.zshrc
    echo "alias fd='fdfind'" >> ~/.localrc
  fi
}

install() {
  ./create-symlinks

  git clone --depth=1 https://github.com/romkatv/gitstatus.git $HOME/git/gitstatus
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --key-bindings --completion --update-rc
}

main() {
  pre_install
  install
}

main
